// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Btree_sum
NumericVector Btree_sum(IntegerVector y, NumericVector z);
RcppExport SEXP _energy_Btree_sum(SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(Btree_sum(y, z));
    return rcpp_result_gen;
END_RCPP
}
// calc_dist
NumericMatrix calc_dist(NumericMatrix x);
RcppExport SEXP _energy_calc_dist(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_dist(x));
    return rcpp_result_gen;
END_RCPP
}
// U_product
double U_product(NumericMatrix U, NumericMatrix V);
RcppExport SEXP _energy_U_product(SEXP USEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type U(USEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(U_product(U, V));
    return rcpp_result_gen;
END_RCPP
}
// D_center
NumericMatrix D_center(NumericMatrix Dx);
RcppExport SEXP _energy_D_center(SEXP DxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Dx(DxSEXP);
    rcpp_result_gen = Rcpp::wrap(D_center(Dx));
    return rcpp_result_gen;
END_RCPP
}
// U_center
NumericMatrix U_center(NumericMatrix Dx);
RcppExport SEXP _energy_U_center(SEXP DxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Dx(DxSEXP);
    rcpp_result_gen = Rcpp::wrap(U_center(Dx));
    return rcpp_result_gen;
END_RCPP
}
// dcovU_stats
NumericVector dcovU_stats(NumericMatrix Dx, NumericMatrix Dy);
RcppExport SEXP _energy_dcovU_stats(SEXP DxSEXP, SEXP DySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Dx(DxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dy(DySEXP);
    rcpp_result_gen = Rcpp::wrap(dcovU_stats(Dx, Dy));
    return rcpp_result_gen;
END_RCPP
}
// kgroups_start
List kgroups_start(NumericMatrix x, int k, IntegerVector clus, int iter_max, bool distance);
RcppExport SEXP _energy_kgroups_start(SEXP xSEXP, SEXP kSEXP, SEXP clusSEXP, SEXP iter_maxSEXP, SEXP distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type clus(clusSEXP);
    Rcpp::traits::input_parameter< int >::type iter_max(iter_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type distance(distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(kgroups_start(x, k, clus, iter_max, distance));
    return rcpp_result_gen;
END_RCPP
}
// partial_dcor
NumericVector partial_dcor(NumericMatrix Dx, NumericMatrix Dy, NumericMatrix Dz);
RcppExport SEXP _energy_partial_dcor(SEXP DxSEXP, SEXP DySEXP, SEXP DzSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Dx(DxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dy(DySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dz(DzSEXP);
    rcpp_result_gen = Rcpp::wrap(partial_dcor(Dx, Dy, Dz));
    return rcpp_result_gen;
END_RCPP
}
// partial_dcov
double partial_dcov(NumericMatrix Dx, NumericMatrix Dy, NumericMatrix Dz);
RcppExport SEXP _energy_partial_dcov(SEXP DxSEXP, SEXP DySEXP, SEXP DzSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Dx(DxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dy(DySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dz(DzSEXP);
    rcpp_result_gen = Rcpp::wrap(partial_dcov(Dx, Dy, Dz));
    return rcpp_result_gen;
END_RCPP
}
// poisMstat
NumericVector poisMstat(IntegerVector x);
RcppExport SEXP _energy_poisMstat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(poisMstat(x));
    return rcpp_result_gen;
END_RCPP
}
// projection
NumericMatrix projection(NumericMatrix Dx, NumericMatrix Dz);
RcppExport SEXP _energy_projection(SEXP DxSEXP, SEXP DzSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Dx(DxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dz(DzSEXP);
    rcpp_result_gen = Rcpp::wrap(projection(Dx, Dz));
    return rcpp_result_gen;
END_RCPP
}
