# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Btree_sum <- function(y, z) {
    .Call(`_energy_Btree_sum`, y, z)
}

calc_dist <- function(x) {
    .Call(`_energy_calc_dist`, x)
}

U_product <- function(U, V) {
    .Call(`_energy_U_product`, U, V)
}

D_center <- function(Dx) {
    .Call(`_energy_D_center`, Dx)
}

U_center <- function(Dx) {
    .Call(`_energy_U_center`, Dx)
}

dcovU_stats <- function(Dx, Dy) {
    .Call(`_energy_dcovU_stats`, Dx, Dy)
}

kgroups_start <- function(x, k, clus, iter_max, distance) {
    .Call(`_energy_kgroups_start`, x, k, clus, iter_max, distance)
}

mvnEstat <- function(y) {
    .Call(`_energy_mvnEstat`, y)
}

partial_dcor <- function(Dx, Dy, Dz) {
    .Call(`_energy_partial_dcor`, Dx, Dy, Dz)
}

partial_dcov <- function(Dx, Dy, Dz) {
    .Call(`_energy_partial_dcov`, Dx, Dy, Dz)
}

projection <- function(Dx, Dz) {
    .Call(`_energy_projection`, Dx, Dz)
}

